stages:
  - build
  
image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_REPO: 'luisnabais/cloudflare-ddns'
  BUILDX_VERSION: "v0.11.2"
  BUILDX_URL: "https://github.com/docker/buildx/releases/download/${BUILDX_VERSION}/buildx-${BUILDX_VERSION}.linux-amd64"
  BUILDX_PLATFORMS: "linux/amd64,linux/arm64/v8"


docker-build:
  stage: build
  before_script:
    - wget -O /usr/bin/docker-buildx ${BUILDX_URL}
    - chmod +x /usr/bin/docker-buildx
    - docker login -u ${DOCKER_USER} -p ${DOCKER_TOKEN}
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
  script:
    - docker-buildx create --use
    - docker buildx build
      --provenance=false
      --platform ${BUILDX_PLATFORMS}
      --tag ${CI_REGISTRY_IMAGE}:latest
      --tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
      --tag ${DOCKER_REPO}:latest
      --tag ${DOCKER_REPO}:${CI_COMMIT_TAG}
      --push
      .
  rules:
    - if: $CI_COMMIT_TAG