name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag luisnabais/cloudflare-ddns:1.0
    - name: Push Image to Docker Registry
      run: docker image push luisnabais/cloudflare-ddns:latest
